namespace Shared
{
    public class Character
    {
        public string Sex { get; set; }
        public long HeadType { get; set; }
        public long BodyType { get; set; }
        public long LegsType { get; set; }
        public double HeadSize { get; set; }
        public double EyeBrowH { get; set; }
        public double EyeBrowW { get; set; }
        public double EyeBrowD { get; set; }
        public double EarsH { get; set; }
        public double EarsW { get; set; }
        public double EarsD { get; set; }
        public double EarsL { get; set; }
        public double EyeLidH { get; set; }
        public double EyeLidW { get; set; }
        public double EyeD { get; set; }
        public double EyeAng { get; set; }
        public double EyeDis { get; set; }
        public double EyeH { get; set; }
        public double NoseW { get; set; }
        public double NoseS { get; set; }
        public double NoseH { get; set; }
        public double NoseAng { get; set; }
        public double NoseC { get; set; }
        public double NoseDis { get; set; }
        public double CheekBonesH { get; set; }
        public double CheekBonesW { get; set; }
        public double CheekBonesD { get; set; }
        public double MouthW { get; set; }
        public double MouthD { get; set; }
        public double MouthX { get; set; }
        public double MouthY { get; set; }
        public double ULiphH { get; set; }
        public double ULiphW { get; set; }
        public double ULiphD { get; set; }
        public double LLiphH { get; set; }
        public double LLiphW { get; set; }
        public double LLiphD { get; set; }
        public double JawH { get; set; }
        public double JawW { get; set; }
        public double JawD { get; set; }
        public double ChinH { get; set; }
        public double ChinW { get; set; }
        public double ChinD { get; set; }
        public long Beard { get; set; }
        public long Hair { get; set; }
        public long Body { get; set; }
        public long Waist { get; set; }
        public long Eyes { get; set; }
        public double Scale { get; set; }
        public int Eyebrows_visibility { get; set; }
        public int Eyebrows_tx_id { get; set; }
        public int Scars_visibility { get; set; }
        public int Scars_tx_id { get; set; }
        public int Spots_visibility { get; set; }
        public int Spots_tx_id { get; set; }
        public int Disc_visibility { get; set; }
        public int Disc_tx_id { get; set; }
        public int Complex_visibility { get; set; }
        public int Complex_tx_id { get; set; }
        public int Acne_visibility { get; set; }
        public int Acne_tx_id { get; set; }
        public int Ageing_visibility { get; set; }
        public int Ageing_tx_id { get; set; }
        public int Freckles_visibility { get; set; }
        public int Freckles_tx_id { get; set; }
        public int Moles_visibility { get; set; }
        public int Moles_tx_id { get; set; }
        public int Grime_visibility { get; set; }
        public int Grime_tx_id { get; set; }
        public int Lipsticks_visibility { get; set; }
        public int Lipsticks_tx_id { get; set; }
        public int Lipsticks_palette_id { get; set; }
        public int Lipsticks_palette_color_primary { get; set; }
        public int Shadows_visibility { get; set; }
        public int Shadows_tx_id { get; set; }
        public int Shadows_palette_id { get; set; }
        public int Shadows_palette_color_primary { get; set; }
        public long Albedo { get; set; }
    }
}
